# Generated by Django 5.1.6 on 2025-02-08 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время выполнения заказа",
            ),
            preserve_default=False,
        ),
    ]
