# Generated by Django 5.1.6 on 2025-02-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0002_work_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="", verbose_name="Фото объекта")),
                (
                    "work_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ribaApp.work",
                    ),
                ),
            ],
        ),
    ]
