# Generated by Django 5.1.6 on 2025-02-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0003_workpic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpic",
            name="work_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="ribaApp.work",
            ),
        ),
    ]
