# Generated by Django 5.1.6 on 2025-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0004_alter_workpic_work_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_bottom",
            field=models.CharField(
                default="descr",
                max_length=500,
                verbose_name="Краткое описание для карточки внизу",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="url_title",
            field=models.CharField(
                default="urls",
                max_length=100,
                verbose_name="Название услуги для ссылки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(
                max_length=500,
                verbose_name="Краткое описание для карточки рядом с картинкой",
            ),
        ),
    ]
