# Generated by Django 5.1.6 on 2025-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0005_service_description_bottom_service_url_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="customer",
        ),
        migrations.AddField(
            model_name="test",
            name="customer_name",
            field=models.CharField(
                default="name", max_length=100, verbose_name="Имя заказчика"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="test",
            name="customer_number",
            field=models.CharField(
                default="number", max_length=15, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
    ]
