# Generated by Django 5.1.6 on 2025-02-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0007_question_answer_testresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_correct",
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MC", "Несколько вариантов"),
                    ("SC", "Один вариант"),
                    ("O", "Открытый ответ"),
                ],
                default="SC",
                max_length=2,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.CreateModel(
            name="OpenAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Ответ пользователя")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ribaApp.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "test_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ribaApp.testresult",
                        verbose_name="Результат теста",
                    ),
                ),
            ],
        ),
    ]
