# Generated by Django 5.1.6 on 2025-02-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0008_remove_answer_is_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="test",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="ribaApp.testresult",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ribaApp.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
