# Generated by Django 5.1.6 on 2025-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0009_alter_order_test_testresult_customer_delete_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="expected_answer_type",
            field=models.CharField(
                choices=[("text", "Текст"), ("number", "Число")],
                default="text",
                max_length=10,
                verbose_name="Ожидаемый тип открытого ответа",
            ),
        ),
    ]
