# Generated by Django 5.1.6 on 2025-02-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ribaApp", "0011_remove_order_test_order_service_order_test_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="ribaApp.customer",
            ),
        ),
    ]
