version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: riba
      POSTGRES_USER: riba
      POSTGRES_PASSWORD: riba
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  postgres_data:
