version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh"

volumes:
  static_volume:
  certbot-etc:
  certbot-var:
version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh"

volumes:
  static_volume:
  certbot-etc:
  certbot-var:
