version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: ./entrypoint.sh
    volumes:
      - ./:/ribaGroup
      - static_volume:/ribaGroup/staticfiles

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume: